simplehttp:simplehttp.cpp
	g++ simplehttp.cpp -lcurl -liconv -I/Users/tianyang/Downloads/boost_1_59_0  -L/Users/tianyang/Downloads/boost_1_59_0/stage/lib -lboost_regex -o simplehttp

clean:
	rm -f *.o *~ *# simplehttp
